/*
Copyright (c) 2016 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module pbr;

import std.stdio;

import dlib.core.memory;
import dlib.core.stream;
import dlib.math.vector;
import dlib.math.affine;
import dlib.math.quaternion;
import dlib.math.utils;
import dlib.image.color;
import dlib.filesystem.filesystem;

import dgl.core.api;
import dgl.core.event;
import dgl.core.application;
import dgl.core.interfaces;

import dgl.templates.app3d;
import dgl.templates.freeview;

import dgl.graphics.entity;
import dgl.graphics.camera;
import dgl.graphics.shapes;
import dgl.graphics.material;
import dgl.graphics.texture;
import dgl.graphics.shader;
import dgl.graphics.shadow;
import dgl.graphics.state;
import dgl.graphics.light;
import dgl.graphics.pbrshader;

import dgl.asset.dgl3;
import dgl.asset.envtexture;

class EnvironmentSphere: Drawable
{
    Camera camera;
    ShapeSphere sphere;
    float radius = 50.0f;
    
    this(Camera cam)
    {
        camera = cam;
        sphere = New!ShapeSphere(1);
    }
    
    void draw(double dt)
    {
        glPushMatrix();
        Vector3f pos = camera.getTransformation.translation;
        glTranslatef(pos.x, pos.y, pos.z);
        glRotatef(180.0f, 0, 1, 0);
        glRotatef(-90.0f, 1, 0, 0);
        glScalef(-radius, -radius, -radius);
        glDisable(GL_LIGHTING);
        glDepthMask(GL_FALSE);
        sphere.draw(dt);
        glDepthMask(GL_TRUE);
        glEnable(GL_LIGHTING);
        glPopMatrix();
    }
    
    ~this()
    {
        Delete(sphere);
    }
}

enum SHADOW_GROUP = 100;

class Simple3DApp: Application3D
{
    Freeview freeview;
    DGL3Resource model;
    
    ShadowMapPass shadow; 
    
    PBRShader pbrShader;
    
    EnvironmentSphere envSphere;
    Material envMat;
    
    EnvTextureResource ambTexRes;
    
    this()
    {
        super();

        Quaternionf sunLightRot = 
            rotationQuaternion(1, degtorad(0.0f)) *
            rotationQuaternion(0, degtorad(-30.0f));

        if (useShadows)
        {
            PipelineState.shadowMapSize = 2048;
            shadow = New!ShadowMapPass(PipelineState.shadowMapSize, scene3d, SHADOW_GROUP, eventManager);
            addPass3D(shadow);
            shadow.lightRotation = sunLightRot;
            shadow.projectionSize = 20;
        }

        LightManager.sunEnabled = true;
        LightManager.sunPosition = Vector4f(sunLightRot.rotate(Vector3f(0, 0, 1)));
        LightManager.sunPosition.w = 0.0f;
        LightManager.sunColor = Color4f(0.9, 0.9, 0.8, 1);
        
        Material.setFogDistance(50, 200);
        Material.setFogColor(Color4f(0.5, 0.8, 1.0, 1.0));
        
        setDefaultLoadingImage("data/loading.png");
        
        mountDirectory("data");
        mountDirectory("data/cerberus");

        ambTexRes = addEnvironmentTexureResource("zion-sunsetpeek.png");
        model = addModelResource("cerberus.dgl3");
        
        loadResources();
        
        freeview = New!Freeview(eventManager);
        
        envSphere = New!EnvironmentSphere(freeview.camera);
        auto envSphereEntity = createEntity3D(envSphere);
        envMat = New!Material();
        envMat.textures[0] = ambTexRes.texture;
        envSphereEntity.material = envMat;
        
        pbrShader = New!PBRShader;
                
        addEntitiesFromModel(model);
    }
    
    EnvTextureResource addEnvironmentTexureResource(string filename)
    {
        EnvTextureResource res = New!EnvTextureResource(resourceManager.imageFactory);
        resourceManager.addResource(filename, res);
        return res;
    }

    ~this()
    {
        Delete(pbrShader);
        Delete(freeview);
        Delete(envSphere);
        Delete(envMat);
    }
    
    override void onUpdate(double dt)
    {
        super.onUpdate(dt);

        freeview.update();
        setCameraMatrix(freeview.getCameraMatrix());
        
        if (Material.uberShader)
            Material.uberShader.setViewMatrix(freeview.camera);
        if (pbrShader)
            pbrShader.setViewMatrix(freeview.camera);
        
        if (shadow)
            shadow.update(dt);
    }
    
    override void onRedraw(double dt)
    {
        if (shadow)
            shadow.bind(freeview.camera.getTransformation());       
        super.onRedraw(dt);
        if (shadow)
            shadow.unbind();
    }

    void addEntitiesFromModel(DGL3Resource model)
    {
        foreach(e; model.entities)
        {
            if (useShadows)
                e.groupID = SHADOW_GROUP;

            addEntity3D(e);

            if (e.material)
            {
                if (useShaders)
                {
                    e.material.setShader(pbrShader);                    
                    ambTexRes.applyToMaterial(e.material);
                }
                else
                {
                    e.material.textures[1] = null;
                    e.material.textures[2] = null;
                    e.material.textures[3] = null;
                    e.material.textures[4] = null;
                }
            }
        }
    }

    override void onKeyDown(int key)
    {
        if (key == SDLK_ESCAPE)
        {
            exit();
        }
    }
}

void main()
{
    writefln("Allocated memory: %s byte(s)", allocatedMemory);
    initDGL();
    auto app = New!Simple3DApp();
    app.run();
    Delete(app);
    deinitDGL();
    writefln("Allocated memory: %s byte(s)", allocatedMemory);
}
